### ISSUE TITLE
Invalid redirect http://beth-authcode-sample.cfapps.io/login did not match one of the registered values

### ISSUE THREAD

**Issue by betht1220** [pivotal-cf/identity-sample-apps#1]
I've done the followings and ran into issue 
1. click at app link
2. presented with index.html
3. click at the link on index.html
4. presented with login screen, and entered correct pws user/pass
5. presented with error page
    a. address bar display = https://btran.login.run.pivotal.io/oauth/authorize?client_id=96a2b234-23ea-49ce-8a3e-ac63c7df3f8f&redirect_uri=http://beth-authcode-sample.cfapps.io/login&response_type=code&state=h8XHaJ
    b. error  on page = Invalid redirect http://beth-authcode-sample.cfapps.io/login did not match one of the registered values
6. the redirect path http://beth-authcode-sample.cfapps.io/login is not in the code

**Comment by khuang-pivotal** [comment]
@betht1220 You should be using https instead of http. When you click on the app link, ensure that you are using https prior to authenticating.

We will update the sample apps to have the correct https app links.

**Comment by betht1220** [comment]
Yes, thank you khuang.  That was the problem.
Regarding client_credentials, after the app gets the "access token", specifically which resources can it access using this access token? 
I tried to get https://<authdomain-url>/userinfo, but got error
Invalid token does not contain resource id (openid)

**Comment by tnwang** [comment]
Userinfo endpoint requires `openid` scope as described here: https://docs.cloudfoundry.org/api/uaa/version/4.6.0/index.html#user-info
