### ISSUE TITLE
PCF SSO auto redirect URI

### ISSUE THREAD

**Issue by KalyanVudath** [pivotal-cf/identity-sample-apps#12]
I created an app and binded the app with PCF SSO. By default redirect URI has the same URL as of application launch URL. when I give a different URL in Auto Redirect URI. I am getting the error.

Invalid redirect https://<samplesso.pcf.com>/login did not match one of the registered values.

This url is my Application launch URL

**Comment by tnwang** [comment]
Redirect URIs are filtered through a whitelist as mandated by OAuth spec. You need to configure the redirect URI to be part of your whitelist to prevent users from being maliciously redirected to other URLs. Any redirect URI that is not whitelisted will return the error properly.

To configure the redirect URI whitelist, refer to https://docs.pivotal.io/p-identity/configure-apps/index.html. You can either add the redirect URI to your manifest (`SSO_REDIRECT_URIS`) or via the SSO app developer dashboard (**Auth Redirect** URIs beneath **Redirect URIs**).
