### ISSUE TITLE
Reading Custom SSO attributes

### ISSUE THREAD

**Issue by rojagadeesh** [pivotal-cf/identity-sample-apps#16]
I requested my LDAP team to give additional user details.  After that, I'm struggling to read the additional details from SAML response.  What Java class/object would require

**Comment by tnwang** [comment]
Spring Boot 2.1 will support it as referenced in https://www.baeldung.com/spring-security-oauth-principal-authorities-extractor

Alternatively for 1.5, the information will also be available in either the ID token object, or from the response from the userinfo endpoint. Spring Security folks might have more insight on how 1.5 allowed the authorities extractor pattern to work.
