### ISSUE TITLE
I get HTTP 403 error inside authcode application , when i try to call resource server, please suggest any step i am missing

### ISSUE THREAD

**Issue by naragudipati** [pivotal-cf/identity-sample-apps#17]
GET request for "https://resource-server-sample.pcfapps.nonprod.ptc.nttdataservices.com//todo" resulted in 403 (Forbidden); invoking error handler

**Comment by tnwang** [comment]
Hi @naragudipati, you may need to make sure that the `todo.read` and `todo.write` scopes are available in your application.

For test purposes, these steps let you add them to internal users (https://docs.pivotal.io/p-identity/1-8/configure-id-providers.html#add-to-int) although mapping from external IDPs is also available.

Other things to check: Have you set the AUTH_DOMAIN URI to the same SSO plan/authorization server as the one where the web app is getting the token from?

Hope this helps.
